# Generated by Django 5.1.4 on 2025-01-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('goal', 'date')},
        ),
    ]
